### ISSUE TITLE
Icons are not working in the latest cfd build 0.4.0-build211

### ISSUE THREAD

**Issue by sureshg** [DevSrSouza/compose-icons#7]
```kotlin
  kotlin("jvm") version "1.5.10"
  id("org.jetbrains.compose") version "0.4.0-build211"
```

Throwing the following exception when initializing the icon.

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'void androidx.compose.ui.graphics.vector.ImageVector$Builder.<init>(java.lang.String, float, float, float, float, long, androidx.compose.ui.graphics.BlendMode, int, kotlin.jvm.internal.DefaultConstructorMarker)'
        at compose.icons.simpleicons.KotlinKt.getKotlin(Kotlin.kt:19)
```

**Comment by odvratnozgodan** [comment]
Same issue here. I am using Compose `0.4.0-rc2`.

**Comment by stephanepechard** [comment]
Still the same with Compose Desktop 0.4.0.

**Comment by DevSrSouza** [comment]
With the release of `1.0.0` should work just fine with any Compose Desktop version from 0.4.0 and up.
